/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserExtraInfo service. Represents a row in the &quot;AMF_UserExtraInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.registration.model.impl.UserExtraInfoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.registration.model.impl.UserExtraInfoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserExtraInfo
 * @generated
 */
@ProviderType
public interface UserExtraInfoModel extends BaseModel<UserExtraInfo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user extra info model instance should use the {@link UserExtraInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this user extra info.
	 *
	 * @return the primary key of this user extra info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user extra info.
	 *
	 * @param primaryKey the primary key of this user extra info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user extra info.
	 *
	 * @return the uuid of this user extra info
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user extra info.
	 *
	 * @param uuid the uuid of this user extra info
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the extra info ID of this user extra info.
	 *
	 * @return the extra info ID of this user extra info
	 */
	public long getExtraInfoId();

	/**
	 * Sets the extra info ID of this user extra info.
	 *
	 * @param extraInfoId the extra info ID of this user extra info
	 */
	public void setExtraInfoId(long extraInfoId);

	/**
	 * Returns the user ID of this user extra info.
	 *
	 * @return the user ID of this user extra info
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user extra info.
	 *
	 * @param userId the user ID of this user extra info
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user extra info.
	 *
	 * @return the user uuid of this user extra info
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user extra info.
	 *
	 * @param userUuid the user uuid of this user extra info
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the address of this user extra info.
	 *
	 * @return the address of this user extra info
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this user extra info.
	 *
	 * @param address the address of this user extra info
	 */
	public void setAddress(String address);

	/**
	 * Returns the address2 of this user extra info.
	 *
	 * @return the address2 of this user extra info
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this user extra info.
	 *
	 * @param address2 the address2 of this user extra info
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this user extra info.
	 *
	 * @return the city of this user extra info
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this user extra info.
	 *
	 * @param city the city of this user extra info
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this user extra info.
	 *
	 * @return the state of this user extra info
	 */
	public int getState();

	/**
	 * Sets the state of this user extra info.
	 *
	 * @param state the state of this user extra info
	 */
	public void setState(int state);

	/**
	 * Returns the zip of this user extra info.
	 *
	 * @return the zip of this user extra info
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this user extra info.
	 *
	 * @param zip the zip of this user extra info
	 */
	public void setZip(String zip);

}